version: '3'
services:

      web_service:
        build:
          context: .
          dockerfile: Dockerfile
        hostname: web_service
        container_name: web_service
        depends_on:
          - rabbitmq
        volumes:
          - .:/app/prs_dev
        ports:
          - "8000:8000"
        command: bash -c "python manage.py runserver 0.0.0.0:8000"

      celery_worker:
        build:
          context: .
          dockerfile: Dockerfile
        hostname: celery_worker
        container_name: celery_worker
        depends_on:
          - rabbitmq
        volumes:
          - .:/app/prs_dev
        command: bash -c "celery -A prs_dev worker -l info"

      rabbitmq:
        image: rabbitmq:3.7.3-management
        environment:
          RABBITMQ_DEFAULT_USER: celery 
          RABBITMQ_DEFAULT_PASS: password
          RABBITMQ_DEFAULT_VHOST: my_vhost
        ports:
          - "5672:5672"
          - "15672:15672"
