# Generated by Django 2.2.2 on 2020-10-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginformation',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
